version:  '3'

services:
  web_server:

    container_name: web_server

    build:
      context:  requierements/nginx 

    ports:
      - "443:443"

    environment:
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - NGINX_CONFIG_DIR=${NGINX_CONFIG_DIR}
      - SERVER_NAME=${SERVER_NAME}
