version:  '3'

services:
  server:

    container_name: nginx 
    build:
      context:  requierements/nginx 
      args:
        - SSL_KEY_PATH=${SSL_KEY_PATH}
        - SSL_CERT_PATH=${SSL_CERT_PATH}
    volumes:
      - /home/plouvel/data/html:/var/www/html
    ports:
      - "443:443"
    restart: always
    networks:
      - backend
    environment:
      - WAIT_HOSTS=wordpress:9000
      - WAIT_LOGGER_LEVEL=off
      - WP_PATH=${WP_PATH}
      - ADM_PATH=${ADM_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - NGINX_CONFIG_DIR=${NGINX_CONFIG_DIR}
      - SERVER_NAME=${SERVER_NAME}

  wordpress:
    container_name: wordpress
    volumes:
      - /home/plouvel/data/html:/var/www/html
    build:
      context:  requierements/wordpress
    restart: always
    networks:
      - backend
    environment:
      - WAIT_HOSTS=database:3306
      - WAIT_LOGGER_LEVEL=off
      - WP_PATH=${WP_PATH}
      - WP_BLOG_TITLE=${WP_BLOG_TITLE}
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_DB_USER=${WP_DB_USER}
      - WP_DB_USER_PWD=${WP_DB_USER_PWD}
      - WP_ADMIN_NAME=${WP_ADMIN_NAME}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}

  cache:
    container_name: redis 
    build:
      context:  requierements/redis
    restart: always
    networks:
      - backend
    environment:
      - WAIT_HOSTS=database:3306, wordpress:9000
      - WAIT_LOGGER_LEVEL=off

  database:

    container_name: mariadb
    build:
      context:  requierements/mariadb
    volumes:
      - /home/plouvel/data/mysql:/var/lib/mysql
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PWD=${MYSQL_ROOT_PWD}
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_DB_USER=${WP_DB_USER}
      - WP_DB_USER_PWD=${WP_DB_USER_PWD}

networks:
  backend:
    driver: bridge
