version:  '3.8'

services:
  server:

    container_name: nginx 
    build:
      context:  requierements/nginx 
      args:
        - SSL_KEY_PATH=${SSL_KEY_PATH}
        - SSL_CERT_PATH=${SSL_CERT_PATH}
    volumes:
      - wp-data:/var/www/html/wordpress 
      - adminer-data:/var/www/html/adminer
      - perso-data:/var/www/html/perso
    ports:
      - "443:443"
    restart: always
    networks:
      - wp-site
    depends_on:
      - wordpress
    environment:
      - WAIT_HOSTS=wordpress:9000, adminer:9000
      - WAIT_LOGGER_LEVEL=off
      - WP_PATH=${WP_PATH}
      - ADM_PATH=${ADM_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - NGINX_CONFIG_DIR=${NGINX_CONFIG_DIR}
      - SERVER_NAME=${SERVER_NAME}

  wordpress:
    container_name: wordpress
    volumes:
      - wp-data:/var/www/html/wordpress 
    build:
      context:  requierements/wordpress
    depends_on:
      - database
    restart: always
    networks:
      - wp-site
    environment:
      - WAIT_HOSTS=database:3306
      - WAIT_LOGGER_LEVEL=off
      - WP_PATH=${WP_PATH}
      - WP_BLOG_TITLE=${WP_BLOG_TITLE}
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_DB_USER=${WP_DB_USER}
      - WP_DB_USER_PWD=${WP_DB_USER_PWD}
      - WP_ADMIN_NAME=${WP_ADMIN_NAME}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}

  cache:
    container_name: redis 
    build:
      context:  requierements/redis
    restart: always
    depends_on:
      - wordpress
    networks:
      - wp-site
    environment:
      - WAIT_HOSTS=database:3306, wordpress:9000
      - WAIT_LOGGER_LEVEL=off

  database:

    container_name: mariadb
    build:
      context:  requierements/mariadb
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - wp-site
    environment:
      - MYSQL_ROOT_PWD=${MYSQL_ROOT_PWD}
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_DB_USER=${WP_DB_USER}
      - WP_DB_USER_PWD=${WP_DB_USER_PWD}

  adminer:

    container_name: adminer
    build:
      context:  requierements/adminer
    volumes:
      - adminer-data:/var/www/html/adminer
    restart: always
    depends_on:
      - database
    networks:
      - wp-site
    environment:
      - WAIT_HOSTS=database:3306
      - WAIT_LOGGER_LEVEL=off
      - ADM_PATH=${ADM_PATH}
      - ADM_MYSQL_DOWNLOAD_LINK=${ADM_MYSQL_DOWNLOAD_LINK}

  ftp:
    container_name: vsftpd
    build:
      context:  requierements/vsftpd
      args:
        - SSL_FTP_KEY_PATH=${SSL_FTP_KEY_PATH}
        - SSL_FTP_CERT_PATH=${SSL_FTP_CERT_PATH}
        - FTP_USER_NAME=${FTP_USER_NAME}
        - FTP_USER_PWD=${FTP_USER_PWD}
    volumes:
      - wp-data:/var/www/html/wordpress 
    ports:
      - "20:20"
      - "21:21"
      - "21000:21000"
    depends_on:
      - wordpress
    restart: always
    tty: true
    networks:
      - misc
    environment:
      - SSL_FTP_KEY_PATH=${SSL_FTP_KEY_PATH}
      - SSL_FTP_CERT_PATH=${SSL_FTP_CERT_PATH}
      - FTP_USER_NAME=${FTP_USER_NAME}

networks:
  wp-site:
    driver: bridge
  misc:
    driver: bridge

volumes:
  wp-data:
    name: wp-data
    driver_opts:
      type: none
      device: "/home/plouvel/data/wp"
      o: bind
  adminer-data:
    name: adminer-data
    driver_opts:
      type: none
      device: "/home/plouvel/data/adminer"
      o: bind
  mysql-data:
    name: mysql-data
    driver_opts:
      type: none
      device: "/home/plouvel/data/mysql"
      o: bind
  perso-data:
    name: perso-data
    driver_opts:
      type: none
      device: "/home/plouvel/data/perso"
      o: bind
